#!/bin/bash
set -ex
source ./environment
echo building $docker_tag

[ -e secrets.txt ] && rm secrets.txt

cat << EOT >> secrets.txt
export CACHE_GIT_URL=$CACHE_GIT_URL
export CACHE_ARCHIVE=$CACHE_ARCHIVE
export CACHE_BRANCH=$CACHE_BRANCH
EOT

DOCKER_BUILDKIT=1 docker build \
    -t $docker_tag \
    -t $docker_latest \
    --build-arg OPENCV_VERSION=$opencv_version \
    --build-arg OPENCV_DO_TEST="FALSE" \
    --build-arg OPENCV_BUILD_JOBS="4" .
    --secret id=secrets,src="$(pwd)/secrets.txt" \
    .
