#!/bin/bash
set -ex
source ./environment
echo building $docker_tag

[ -e secrets.txt ] && rm secrets.txt

echo "export CACHE_GIT_URL=$CACHE_GIT_URL" >> secrets.txt
echo "export CACHE_ARCHIVE=$CACHE_ARCHIVE" >> secrets.txt
echo "export CACHE_BRANCH=$CACHE_BRANCH" >> secrets.txt

ls -al $(pwd)/secrets.txt
DOCKER_BUILDKIT=1 docker build \
    -t $docker_tag \
    -t $docker_latest \
    --build-arg OPENCV_VERSION=$opencv_version \
    --build-arg OPENCV_DO_TEST="FALSE" \
    --build-arg OPENCV_BUILD_JOBS="10" \
    --secret id=secrets,src="$(pwd)/secrets.txt" \
    .
