#!/bin/bash
set -ex
source ./environment
echo building $docker_tag
docker pull $docker_latest | true

docker build -t $docker_tag -t $docker_latest \
    --build-arg OPENCV_VERSION=$opencv_version \
    --build-arg OPENCV_DO_TEST="FALSE" \
    --build-arg OPENCV_BUILD_JOBS="4" .
